//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyamNyam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneRechept
    {
        public int Id { get; set; }
        public Nullable<int> RecheptId { get; set; }
        public Nullable<int> IngredientId { get; set; }
        public Nullable<double> Kol { get; set; }
        public Nullable<int> MainInitId { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual MainInit MainInit { get; set; }
        public virtual Rechept Rechept { get; set; }
    }
}
