//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyamNyam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechept
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rechept()
        {
            this.OneRechept = new HashSet<OneRechept>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<int> BludoId { get; set; }
        public string Text { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual Bludo Bludo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OneRechept> OneRechept { get; set; }
    }
}
