//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyamNyam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakazAndBludo
    {
        public int Id { get; set; }
        public Nullable<int> BludoId { get; set; }
        public Nullable<int> ZakazId { get; set; }
    
        public virtual Bludo Bludo { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
